### ISSUE TITLE
Swap from or to custom asset does not work since SOR

### ISSUE THREAD

**Issue by vinamogit** [lumenswap/lumenswap.io#114]
Hi,

Just tried the new swap tool and it seems that it breaks all swaps with custom assets.

For example with this asset yXLM:

https://amm.lumenswap.io/swap/XLM/yXLM-GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55

<img width="395" alt="Screenshot 2022-08-19 at 13 32 25" src="https://user-images.githubusercontent.com/49946720/185610625-3e4d0a15-d344-4c68-becc-df58282b1b11.png">

The quote/ api returns a 404 error with message "from asset not found" when using a custom asset (in from or to asset field).

**Comment by amovah** [comment]
Hi
It's fixed now thanks for your report.
