### ISSUE TITLE
Unable to run the Project

### ISSUE THREAD

**Issue by SaadUlHassan** [lumenswap/lumenswap.io#115]
Hi,
I have just cloned the repo tried yarn and the yarn dev. When i open my server at 3000.

I see this screen.
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/41550402/193732801-e8f05bec-f7e5-4b38-bc27-288081dcd148.png">

And i notice there are .env files missing. I copied env variables from demo file inside dockerfiles folder. I paste them and then hit yarn dev. I got some exception.
<img width="1486" alt="image" src="https://user-images.githubusercontent.com/41550402/193733097-de95999b-f455-408c-857c-1733415f7a4a.png">

Can anybody help me in this regard ?

**Comment by SaadUlHassan** [comment]
@amovah

**Comment by amovah** [comment]
you cannot connect to demo, you should you use env from one of productions, like amm or obm.

**Comment by SaadUlHassan** [comment]
Can you share some steps how can i  get them ?

REACT_APP_HORIZON
REACT_APP_LUMENSCAN_URL
REACT_APP_HOST
REACT_APP_LUMEN_API
REACT_APP_ENV
REACT_APP_LOTTERY_ACCOUNT
REACT_APP_LUSI_ISSUER
REACT_APP_DAO_LOCKER_ADDRESS
REACT_APP_L_ISSUER
REACT_APP_OPTIMIZELY_SDK_KEY
REACT_APP_ASSET_CACHE_INTERVAL

Thanks,

**Comment by amovah** [comment]
for amm you can use:
```
ENV REACT_APP_MODE=AMM
ENV REACT_APP_HORIZON=https://horizon.stellar.org
ENV REACT_APP_LUMENSCAN_URL=https://lumenscan.io
ENV REACT_APP_HOST=https://amm.lumenswap.io
ENV REACT_APP_LUMEN_API=https://api.lumenswap.io
ENV REACT_APP_ENV=production
ENV REACT_APP_LOTTERY_ACCOUNT=GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK
ENV REACT_APP_LUSI_ISSUER=GCXSMVCOFOINEEETRTVVGGZRQTVMWT6JSLTR6DXBXZLNYGZSHFXI6V2V
ENV REACT_APP_DAO_LOCKER_ADDRESS=GA35XIM5D4HLVJMHDVD2P6WNPJH7APMW3XONONM2A5EIGQMLRCHZOEZR
ENV REACT_APP_OPTIMIZELY_SDK_KEY=TFYHrVWmbxv3ED4MtVcfF
ENV REACT_APP_PRODUCT_ENV=production
ENV REACT_APP_L_ISSUER=GCT6JZXDCXW5LNVYE6KZP2TSNTDPNGOXPKJW45O7ROC5NSA3O57C6K3X
ENV REACT_APP_ASSET_CACHE_INTERVAL=300000
```

https://github.com/lumenswap/lumenswap.io/blob/master/dockerfiles/amm

**Comment by SaadUlHassan** [comment]
Thanks @amovah. I have used above envs but getting this error.
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/41550402/193784865-79846b7b-6a8d-4c29-83f9-e362b087f90e.png">

I am adding like this.
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/41550402/193785005-10a8efad-edad-4254-b05d-c4ff422d8931.png">

Thank you so much for the help.

**Comment by amovah** [comment]
add this env:
`TOKENS_SERVER_URL=https://api.lumenswap.io`

**Comment by SaadUlHassan** [comment]
Thanks it did worked but now showing. 
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/41550402/193792171-37cdd3c0-ebfa-4d0a-af52-e75f75d03223.png">

**Comment by amovah** [comment]
try `/amm/swap`
