### ISSUE TITLE
Exchanging 2 custom assets doesn't work

### ISSUE THREAD

**Issue by fsodano** [lumenswap/lumenswap.io#41]
Example:

https://obm.lumenswap.io/swap/yXLM-GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55/ARST-GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55

![image](https://user-images.githubusercontent.com/844181/150684622-60eeaa36-0dab-4773-ac58-df74159c3457.png)

**Comment by amovah** [comment]
ARST with GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55 is not valid asset

**Comment by fsodano** [comment]
Hey mate, I'm taking the time to give you feedback that can improve your
product. Did you try with a valid custom asset combination such as yXLM and
yUSDC? It doesn't work.
